export enum Events {
    SPEED_CHANGED,
    INPUT_COMMAND,
    GAME_BEGAN,
    GAME_OVER,
    UPDATE,
    GO_DOWN_ONE_LEVEL,
    TETRAMINO_STACKED_UP,
    CREATE_TETRAMINO,
    COLLECT_STACKED_BLOCKS,
    RANDOMLY_GENERATE_NEXT_TETRAMINO,
}
