export enum Events {
    BLOCK_MOVED,
    SPEED_CHANGED,
    BLOCK_DIED,
    INPUT_COMMAND,
    GAME_BEGAN,
    GAME_OVER,
    FULL_STUCK_CELLS_LIST,
    GO_DOWN_ONE_LEVEL,
    UPDATE,
    CREATE_BLOCK,
    BOARD_CREATE_NEW_BLOCK,
}
