export enum Events {
    SPEED_CHANGED,
    INPUT_COMMAND,
    GAME_BEGAN,
    GAME_OVER,
    UPDATE,
    GO_DOWN_ONE_LEVEL,
    TETRAMINO_STACKED_UP,
    CREATE_BLOCK,
    BOARD_CREATE_NEW_BLOCK,
    RANDOMLY_GENERATE_NEXT_BLOCK,
}
